/**
 * RASH-HIT Fractal Studio - ExcelJS Multi-Sheet Exporter Module
 * STRICT RULE: No direct fetch/XHR calls. Pure client export engine.
 */

window.isExcelLoaded = function() { return typeof ExcelJS !== 'undefined'; };

function exportExcelFromDialogOptions() {
  const scopeEl = document.querySelector('input[name="exportScope"]:checked');
  const styleEl = document.querySelector('input[name="exportStyle"]:checked');
  const scope = scopeEl ? scopeEl.value : 'current';
  const style = styleEl ? styleEl.value : 'both';

  closeExportDialog();
  executeExcelExport(scope, style);
}

function executeExcelExport(scope, style) {
  if (typeof ExcelJS === 'undefined') {
    alert('ExcelJS engine is not available.');
    return;
  }

  let list = [];
  if (scope === 'selected') {
    list = PACKAGES.filter(p => selectedFolders.has(p.folder));
  } else if (scope === 'visible') {
    list = visiblePackages;
  } else if (scope === 'current') {
    list = visiblePackages;
  } else {
    list = PACKAGES;
  }

  if (list.length === 0) {
    alert('No packages found to export.');
    return;
  }

  const wb = new ExcelJS.Workbook();
  wb.creator = 'RASH-HIT Fractal Studio';
  wb.created = new Date();

  buildSummarySheet(wb, list, scope);
  buildPackagesSheet(wb, list);

  if (style === 'both' || style === 'data') {
    buildLevelMetricsSheet(wb, list);
    buildPackageFilesSheet(wb, list);
  }

  const filename = makeExportFileName(scope);
  wb.xlsx.writeBuffer().then(buffer => {
    const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    if (typeof saveAs !== 'undefined') {
      saveAs(blob, filename);
    } else {
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);
    }
  }).catch(err => {
    alert('Excel export error: ' + err.message);
  });
}

function makeExportFileName(scope) {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  const hour = String(now.getHours()).padStart(2, '0');
  const minute = String(now.getMinutes()).padStart(2, '0');
  return `rash_hit_export_${scope}_${year}${month}${day}_${hour}${minute}.xlsx`;
}

function buildSummarySheet(wb, pkgs, scope) {
  const ws = wb.addWorksheet('Summary');
  ws.views = [{ showGridLines: false }];

  // Title rows
  ws.addRow([]);
  ws.addRow(['', 'RASH-HIT Fractal Studio']);
  ws.addRow(['', 'Programmatic Vector-Only Analysis Summary Export']);
  ws.addRow([]);

  // Title styling
  const titleCell = ws.getCell('B2');
  titleCell.font = {
    name: 'Segoe UI',
    family: 2,
    size: 16,
    bold: true,
    color: { argb: 'FF0F172A' }
  };

  const subTitleCell = ws.getCell('B3');
  subTitleCell.font = {
    name: 'Segoe UI',
    family: 2,
    size: 10,
    italic: true,
    color: { argb: 'FF64748B' }
  };

  // Metadata block
  ws.addRow(['', 'EXPORT METADATA']);
  const metaHeader = ws.getCell('B5');
  metaHeader.font = { name: 'Segoe UI', size: 11, bold: true, color: { argb: 'FF0F172A' } };
  metaHeader.border = { bottom: { style: 'medium', color: { argb: 'FF0F172A' } } };

  ws.addRow(['', 'Export Scope:', scope]);
  ws.addRow(['', 'Package Count:', pkgs.length]);
  ws.addRow(['', 'Export Date:', new Date().toLocaleString()]);
  ws.addRow(['', 'Generated By:', 'RASH-HIT Multi-Sheet Engine']);

  for (let i = 6; i <= 9; i++) {
    const keyCell = ws.getCell(`B${i}`);
    const valCell = ws.getCell(`C${i}`);
    keyCell.font = { name: 'Segoe UI', size: 10, bold: true, color: { argb: 'FF475569' } };
    keyCell.alignment = { horizontal: 'right' };
    valCell.font = { name: 'Segoe UI', size: 10, color: { argb: 'FF0F172A' } };
    valCell.alignment = { horizontal: 'left' };
  }

  // Statistical summary block
  ws.addRow([]);
  ws.addRow(['', 'STATISTICAL SUMMARY']);
  const statsHeader = ws.getCell('B11');
  statsHeader.font = { name: 'Segoe UI', size: 11, bold: true, color: { argb: 'FF0F172A' } };
  statsHeader.border = { bottom: { style: 'medium', color: { argb: 'FF0F172A' } } };

  let totalDb = 0;
  let totalR2 = 0;
  let validDbCount = 0;
  let validR2Count = 0;
  pkgs.forEach(p => {
    if (p.db != null) { totalDb += parseFloat(p.db); validDbCount++; }
    if (p.r2 != null) { totalR2 += parseFloat(p.r2); validR2Count++; }
  });
  const avgDb = validDbCount > 0 ? (totalDb / validDbCount) : 0;
  const avgR2 = validR2Count > 0 ? (totalR2 / validR2Count) : 0;

  ws.addRow(['', 'Average Fractal Dimension (Db):', avgDb]);
  ws.addRow(['', 'Average Linear Fit (R²):', avgR2]);

  for (let i = 12; i <= 13; i++) {
    const keyCell = ws.getCell(`B${i}`);
    const valCell = ws.getCell(`C${i}`);
    keyCell.font = { name: 'Segoe UI', size: 10, bold: true, color: { argb: 'FF475569' } };
    keyCell.alignment = { horizontal: 'right' };
    valCell.font = { name: 'Segoe UI', size: 10, bold: true, color: { argb: 'FF2563EB' } };
    valCell.alignment = { horizontal: 'left' };
    valCell.numFmt = '0.0000';
  }

  ws.getColumn('A').width = 4;
  ws.getColumn('B').width = 28;
  ws.getColumn('C').width = 35;
}

function buildPackagesSheet(wb, pkgs) {
  const ws = wb.addWorksheet('Packages');
  ws.addRow(['Motif Name', 'Db (Fractal Dim)', 'R² (Fit)', 'Levels', 'Runtime (ms)', 'Generated Date', 'Folder Path']);

  pkgs.forEach(p => {
    ws.addRow([
      p.motif || '',
      p.db != null ? parseFloat(p.db) : '',
      p.r2 != null ? parseFloat(p.r2) : '',
      p.levels || p.computed_levels_count || '',
      p.total_time_ms != null ? parseFloat(p.total_time_ms) : '',
      p.generated_at || '',
      p.folder || ''
    ]);
  });

  styleTableSheet(ws, [
    { align: 'left', width: 16 },
    { align: 'right', numFmt: '0.0000', width: 15 },
    { align: 'right', numFmt: '0.0000', width: 12 },
    { align: 'right', numFmt: '0', width: 10 },
    { align: 'right', numFmt: '#,##0.00', width: 14 },
    { align: 'center', width: 16 },
    { align: 'left', width: 25 }
  ]);
}

function buildLevelMetricsSheet(wb, pkgs) {
  const ws = wb.addWorksheet('Level Metrics');
  ws.addRow(['Motif Name', 'Folder', 'Level', 'Grid', 'Box W', 'Box H', '1/r', 'Occupied Count', 'Total Count', 'Occupancy %']);

  pkgs.forEach(p => {
    const rows = p.scale_rows || p.scale_table || [];
    if (rows.length > 0) {
      rows.forEach(r => {
        ws.addRow([
          p.motif || '',
          p.folder || '',
          r.level || r.grid_level || '',
          r.grid_label || r.grid || '',
          r.box_size_w || '',
          r.box_size_h || '',
          r.inv_box_size != null ? parseFloat(r.inv_box_size) : '',
          r.occupied_count != null ? r.occupied_count : '',
          r.total_count != null ? r.total_count : '',
          r.occupancy_percent != null ? parseFloat(r.occupancy_percent) / 100 : ''
        ]);
      });
    } else if (p.svg_maps && p.svg_maps.length > 0) {
      p.svg_maps.forEach(m => {
        ws.addRow([
          p.motif || '',
          p.folder || '',
          m.level || '',
          m.grid || '',
          '',
          '',
          '',
          '',
          '',
          ''
        ]);
      });
    }
  });

  styleTableSheet(ws, [
    { align: 'left', width: 16 },
    { align: 'left', width: 20 },
    { align: 'center', width: 10 },
    { align: 'center', width: 12 },
    { align: 'right', numFmt: '#,##0', width: 10 },
    { align: 'right', numFmt: '#,##0', width: 10 },
    { align: 'right', numFmt: '0.00', width: 10 },
    { align: 'right', numFmt: '#,##0', width: 12 },
    { align: 'right', numFmt: '#,##0', width: 12 },
    { align: 'right', numFmt: '0.00%', width: 12 }
  ]);
}

function buildPackageFilesSheet(wb, pkgs) {
  const ws = wb.addWorksheet('Package Files');
  ws.addRow(['Motif Name', 'Folder', 'HTML Report', 'PDF Report', 'Tables Viewer', 'Workbook']);

  pkgs.forEach(p => {
    const f = p.folder || '';
    ws.addRow([
      p.motif || '',
      f,
      p.report_url ? { text: 'Open HTML Report ↗', hyperlink: p.report_url } : '',
      p.report_pdf_url ? { text: 'Open PDF Report ↗', hyperlink: p.report_pdf_url } : '',
      p.tables_url ? { text: 'Open Tables Viewer ↗', hyperlink: p.tables_url } : '',
      p.workbook_url ? { text: 'Open Workbook ↗', hyperlink: p.workbook_url } : ''
    ]);
  });

  styleTableSheet(ws, [
    { align: 'left', width: 16 },
    { align: 'left', width: 20 },
    { align: 'left', width: 22 },
    { align: 'left', width: 22 },
    { align: 'left', width: 22 },
    { align: 'left', width: 22 }
  ]);
}

/** ExcelJS worksheet table styler helper */
function styleTableSheet(ws, columnsConfig) {
  ws.views = [{ showGridLines: true }];

  // Style Header Row (Row 1)
  const headerRow = ws.getRow(1);
  headerRow.height = 28;
  headerRow.eachCell((cell, colNum) => {
    cell.font = {
      name: 'Segoe UI',
      family: 2,
      size: 11,
      bold: true,
      color: { argb: 'FFFFFFFF' }
    };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF0F172A' } // Sleek navy/slate header background
    };
    cell.alignment = {
      vertical: 'middle',
      horizontal: columnsConfig[colNum - 1]?.align || 'left',
      wrapText: true
    };
    cell.border = {
      top: { style: 'thin', color: { argb: 'FF475569' } },
      left: { style: 'thin', color: { argb: 'FF475569' } },
      bottom: { style: 'medium', color: { argb: 'FF0F172A' } },
      right: { style: 'thin', color: { argb: 'FF475569' } }
    };
  });

  // Style Data Rows
  ws.eachRow((row, rowNum) => {
    if (rowNum === 1) return; // Skip header

    row.height = 22;
    const isEven = rowNum % 2 === 0;

    row.eachCell((cell, colNum) => {
      const config = columnsConfig[colNum - 1] || {};
      const isHyperlink = cell.value && cell.value.hyperlink;

      // Font
      cell.font = {
        name: 'Segoe UI',
        family: 2,
        size: 10,
        color: isHyperlink ? { argb: 'FF2563EB' } : { argb: 'FF334155' },
        underline: isHyperlink ? true : false
      };

      // Zebra striping
      if (isEven) {
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFF8FAFC' }
        };
      }

      // Alignment
      cell.alignment = {
        vertical: 'middle',
        horizontal: config.align || 'left'
      };

      // Number Formatting
      if (config.numFmt) {
        cell.numFmt = config.numFmt;
      }

      // Borders
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } }
      };
    });
  });

  // Auto column widths
  ws.columns.forEach((column, index) => {
    const config = columnsConfig[index] || {};
    let maxLength = config.width || 12;
    column.eachCell({ includeEmpty: true }, (cell) => {
      let cellLength = 0;
      if (cell.value) {
        if (cell.value.text && cell.value.hyperlink) {
          cellLength = cell.value.text.toString().length;
        } else {
          cellLength = cell.value.toString().length;
        }
      }
      if (cellLength > maxLength) {
        maxLength = cellLength;
      }
    });
    column.width = Math.min(Math.max(maxLength + 3, 10), 40);
  });
}
